apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgresql-k8s
  labels:
    app: postgresql-k8s
    app.openshift.io/runtime: postgresql

spec:

  serviceName: postgresql-k8s

  replicas: 1

  selector:
    matchLabels:
      app: postgresql-k8s

  template:
    metadata:
      labels:
        app: postgresql-k8s
        
    spec:

      serviceAccountName: postgresql-k8s-sa

      securityContext:
        fsGroup: 26 
      
      containers:

        - name: postgresql-k8s
          image: registry.redhat.io/rhel9/postgresql-16
          imagePullPolicy: Always

          ports:
            - containerPort: 5432
              protocol: TCP

          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-k8s-configs
                  key: POSTGRESQL_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-k8s-configs
                  key: POSTGRESQL_PASSWORD
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgresql-k8s-configs
                  key: POSTGRESQL_DATABASE

          resources:
            limits:
              cpu: 1500m
              memory: 2Gi
            requests:
              cpu: 1500m
              memory: 2Gi

          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/pgsql/data

  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi