kind: Service
apiVersion: v1
metadata:
  name: mssql-k8s
  labels:
    app: mssql-k8s
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 1433-tcp
      protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
  selector:
    app: mssql-k8s